# Generated by Django 3.0.8 on 2020-10-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=10)),
                ('comentario', models.CharField(max_length=2000)),
            ],
        ),
    ]
