# Generated by Django 3.0.8 on 2020-11-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0003_auto_20201031_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_posicion',
            name='codigo_producto',
        ),
        migrations.RemoveField(
            model_name='pedido_posicion',
            name='numero_pedido',
        ),
        migrations.DeleteModel(
            name='Pedido_cabecera',
        ),
        migrations.DeleteModel(
            name='Pedido_posicion',
        ),
    ]
