# Generated by Django 3.1.2 on 2020-11-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0004_auto_20201031_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numero_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('valor', models.IntegerField()),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
